# Generated by Django 3.2.9 on 2022-02-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220205_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profileimg'),
        ),
    ]
